baseURL: "https://http4k.org"
languageCode: "en-us"
publishDir: "../../build/www"

title: "http4k"

summaryLength: 20

markup:
  asciidocExt:
    attributes:
      sectlinks: true
  goldmark:
    renderer:
      unsafe: true

  highlight:
    style: "monokai"
    lineNos: false

params:
  title: "http4k"
  description: "The Functional toolkit for Kotlin HTTP applications"
  logo: "/images/logo.png"
  logoSvg: "/images/logo.svg"
  images:
    - "/images/social-logo.png"

  versions:
    http4k: "6.0.0.0"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#FFFFFF"

  fathomAnalytics:
    enabled: true
    id: "BGFZWRDS"

  contact:
    email: "info@http4k.org?subject=Get in touch with http4k"

  copyright: "http4k Ltd â€“ All Rights Reserved"

menus:
  nav:
    - name: about
      title: About
      weight: 10
      children:
    - name: about-overview
      title: Overview
      url: /overview/
      parent: about
      weight: 11
    - name: about-news
      title: News
      url: /news/
      parent: about
      weight: 12
    - name: about-showcase
      title: Showcase
      url: /showcase/
      parent: about
      weight: 13

    - name: learn
      title: Learn
      weight: 20
    - name: learn-about-the-docs
      title: About the docs
      url: /learn/
      parent: learn
      weight: 21
    - name: learn-quickstart
      title: Quickstart
      url: /quickstart/
      parent: learn
      weight: 22
    - name: learn-tutorials
      title: Tutorials
      url: /tutorial/
      parent: learn
      weight: 23
    - name: learn-howto
      title: How-to guides
      url: /howto/
      parent: learn
      weight: 24
    - name: learn-performance
      title: Performance
      url: /performance/
      parent: learn
      weight: 25
    - name: learn-faq
      title: FAQ
      url: /faq/
      parent: learn
      weight: 25

    - name: ecosystem
      title: Ecosystem
      weight: 30
    - name: ecosystem-overview
      title: Overview
      url: /ecosystem/
      parent: ecosystem
      weight: 31
    - name: ecosystem-http4k
      title: http4k Core
      url: /ecosystem/http4k/
      parent: ecosystem
      weight: 32
    - name: ecosystem-connect
      title: http4k Connect
      url: /ecosystem/connect/
      parent: ecosystem
      weight: 33
    - name: ecosystem-changelog
      title: Changelog
      url: /ecosystem/changelog/
      parent: ecosystem
      weight: 34

    - name: solutions
      title: Solutions
      weight: 40
    - name: solutions-overview
      title: Overview
      url: /solutions/
      parent: solutions
      weight: 41
    - name: solutions-enterprise
      title: Enterprise Edition
      url: /enterprise/
      parent: solutions
      weight: 42
    - name: solutions-pro
      title: Pro modules
      url: /pro/
      parent: solutions
      weight: 43
    - name: solutions-consulting
      title: Consulting
      url: /consulting/
      parent: solutions
      weight: 44
    - name: solutions-training
      title: Developer Training
      url: /training/
      parent: solutions
      weight: 45
    - name: solutions-slack
      title: Private Slack
      url: "http://http4k.slack.com/"
      parent: solutions
      weight: 46
    - name: solutions-security
      title: Security Advisories
      url: /security/
      parent: solutions
      weight: 47

    - name: community
      title: Community
      weight: 50
    - name: community-contributors
      title: Our Community of Contributors
      url: /community/
      parent: community
      weight: 51
    - name: community-slack
      title: Community Slack
      url: https://kotlinlang.slack.com/archives/C5AL3AKUY
      parent: community
      weight: 52
    - name: community-coc
      title: Code of Conduct
      url: /code-of-conduct/
      parent: community
      weight: 53

    - name: toolbox
      title: Toolbox
      weight: 60
    - name: tools-web
      title: Web
      url: https://toolbox.http4k.org/
      parent: toolbox
      weight: 61
    - name: toolbox-intellij
      title: IntelliJ
      url: https://plugins.jetbrains.com/plugin/25243-http4k-toolbox
      parent: toolbox
      weight: 62
    - name: tools-cli
      title: CLI
      url: https://toolbox.http4k.org/
      parent: toolbox
      weight: 63
  legal:
    - name: "Privacy policy"
      url: /privacy-policy/
      weight: 1
    - name: "Terms & conditions"
      url: /terms-and-conditions/
      weight: 2
    - name: "Disclaimer"
      url: /disclaimer/
      weight: 3

taxonomies:
  module: "module"
  ecosystem: "ecosystem"
  news: "news"
  howto: "howto"
